# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.3

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

AsciiComments:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

RescueModifier:
  Enabled: false

RescueStandardError:
  Enabled: false

MutableConstant:
  Enabled: false

AbcSize:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

IfUnlessModifier:
  Enabled: false

ParameterLists:
  Enabled: false

GuardClause:
  Enabled: false
